### ISSUE TITLE
Enable finding duplicates between decks

### ISSUE THREAD

**Issue by ghost** [quancs/Remove-Duplicate-Cards#1]
I attempted to modify your code in order to enable the identification of duplicates between decks and the ability to choose which deck to retain duplicated cards from. Unfortunately, I am not very proficient in coding (I have just started learning), and I am struggling to find a way to achieve this. If you wouldn't mind, could you possibly consider adding this feature to the add-on? It would be immensely helpful.

**Comment by quancs** [comment]
Sorry, I have no time to implement new functions for this plugin.

**Comment by ghost** [comment]
No problem. Once I become more skilled in coding, I'll implement it myself and submit a PR. I appreciate you answering, though!
